version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.1.4

executors:
  docker-executor:
    docker:
      - image: cimg/node:18.20.0
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Clean & install dependencies
          command: |
            rm -rf node_modules package-lock.json
            npm install

      - run:
          name: Build production code (if needed)
          command: |
            if [ -f package.json ] && grep -q '"build":' package.json; then
              npm run build
            fi

      - setup_remote_docker: {}  # ✅ Removed version field

      - run:
          name: Docker build image
          command: |
            docker build -t face-gender-app .

      - run:
          name: Run Docker container (test)
          command: |
            docker run -d -p 3000:3000 --name face-gender-app-test -v $(pwd)/captures:/app/captures face-gender-app
            sleep 10
            curl -f http://localhost:3000 || echo "App didn't respond as expected"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
